runtime: java
env: flex
service: todos-backend
runtime_config:
  jdk: openjdk8
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 3.75
  disk_size_gb: 10
env_variables:
  PROFILER_ENABLE: true
  SPRING_PROFILES_ACTIVE: cloud
  SPRING_CLOUD_GCP_LOGGING_PROJECT_ID: my-kubernetes-248208